on:
  pull_request:
  push:
    branches:
      - main

name: Continuous integration

jobs:
  ci:
    name: CI
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: ci
